#!/bin/sh

unset GIT_DIR
cd ..

RECEIVE_BRANCH_COUNT=0
while read oldval newval refname
do
    branch=$(git rev-parse --symbolic --abbrev-ref $refname)
    ((RECEIVE_BRANCH_COUNT++))
done
if [ $RECEIVE_BRANCH_COUNT -eq 1 ];then
    git checkout $branch
fi

git reset --hard
